import test from 'node:test';
import assert from 'node:assert/strict';
import { initial } from './state.js';
import { beginProgression, trainingCap } from './progression.js';
import { p0Command, settleActivity, OFFLINE_CAP, settleP0Combat } from './p0-engine.js';
import { startCombat, advanceCombat, retreatCombat } from './combat.js';
import { availableStyles } from '../content/combat.js';
import { encodeSave, migrateSave } from './saves.js';
import { saveOptions } from './save-schema.js';
import { SIDE_EVENTS } from '../content/p0.js';
import { PACK_EVENTS } from '../content/side-packs.js';
import { validateP0 } from '../content/validate-p0.js';
import { createGameReducer } from './commands.js';

const fresh = () => beginProgression(initial());
const at = (s, room, loc = 0) => ({ ...s, loc, p0: { ...s.p0, room } });
const cmd = (s, type, params = {}, now = 1000) => p0Command(s, { type, ...params }, now);
const restore = s => migrateSave(encodeSave(s), saveOptions);
test('content validation rejects missing successors and reward loops without endings', () => {
  assert.ok(validateP0());
  const bad = structuredClone(SIDE_EVENTS);
  bad.medicine.nodes.request.choices[0].next = 'missing';
  assert.throws(() => validateP0(bad), /missing/);
});
test('life work, teaching, training and persistent combat form a resource loop', () => {
  let s = at({ ...fresh(), silver: 0 }, 'dock');
  s.p0.potential = 0;
  s = cmd(s, 'START_ACTIVITY', { id: 'work' });
  s = settleActivity(s, 61000);
  assert.equal(s.silver, 24); assert.equal(s.p0.potential, 16);
  s = at(cmd(s, 'STOP_ACTIVITY', {}, 61000), 'gym');
  s = cmd(s, 'LEARN_SKILL', { id: 'taizu' }, 61000);
  assert.ok(s.p0.styles['太祖长拳']); assert.equal(s.silver, 12); assert.equal(s.p0.potential, 6);
  s = cmd(s, 'START_ACTIVITY', { id: 'style', target: '太祖长拳' }, 61000);
  s = settleActivity(s, 71000);
  assert.equal(s.training.styles['太祖长拳'], 5); assert.equal(s.p0.potential, 1); assert.equal(s.p0.activity, null);
  const fight = startCombat(s);
  assert.equal(fight.battle.player.mp, Math.round(fight.battle.player.maxMp * s.mp / 100));
  const ended = retreatCombat(fight);
  assert.deepEqual(restore(ended), { ...ended, fx: null });
});
test('offline settlement preserves fractions, caps elapsed time and cannot pay the same interval twice', () => {
  const active = cmd(at(fresh(), 'dock'), 'START_ACTIVITY', { id: 'work' });
  const first = settleActivity(active, 10000), second = settleActivity(first, 16000);
  assert.equal(second.silver - active.silver, 6);
  assert.equal(settleActivity(second, 16000).silver, second.silver);
  const offline = cmd(active, 'RESUME', {}, 1000 + 2 * OFFLINE_CAP);
  assert.equal(offline.silver - active.silver, OFFLINE_CAP / 15000 * 6);
  assert.ok(offline.p0.report.capped);
  assert.equal(cmd(restore(offline), 'RESUME', {}, 1000 + 2 * OFFLINE_CAP).silver, offline.silver);
  const back = settleActivity(offline, 0);
  assert.equal(back.silver, offline.silver); assert.equal(back.p0.activity.settledAt, offline.p0.activity.settledAt);
});
test('switching activities settles the old target and training stops at basic or teacher cap', () => {
  let s = at(fresh(), 'dock');
  s = cmd(s, 'START_ACTIVITY', { id: 'work' });
  s = cmd(s, 'START_ACTIVITY', { id: 'basic', target: 'fist' }, 16000);
  assert.equal(s.silver, initial().silver + 6);
  s = settleActivity(s, 36000);
  assert.equal(s.p0.basics.fist, 120);
  s = cmd(s, 'START_ACTIVITY', { id: 'style', target: '基本拳脚' }, 36000);
  s.p0.potential = 500;
  s = settleActivity(s, 1000000);
  assert.equal(s.training.styles['基本拳脚'], 120); assert.equal(s.p0.activity, null);
  assert.equal(trainingCap(s, 'styles', '基本拳脚'), 120);
});
test('fresh characters do not gain arts by leveling; legacy characters retain owned arts', () => {
  const freshHigh = { ...fresh(), expTotal: 40000 };
  assert.ok(!availableStyles(freshHigh).includes('太玄经影'));
  const legacy = beginProgression({ ...initial(), expTotal: 40000 }, true);
  assert.ok(availableStyles(legacy).includes('太玄经影'));
  assert.equal(legacy.p0.styles['太玄经影'].source, '旧日领悟');
  assert.ok(!cmd(at(fresh(), 'gate'), 'LEARN_SKILL', { id: 'liuhe' }).p0.styles['六合刀']);
});
test('fixed dialogue branch leads to actual shop and teaching consequences without duplicate rewards', () => {
  let s = at(fresh(), 'pharmacy');
  s = cmd(s, 'DISCOVER_EVENT', { id: 'medicine' });
  s = cmd(s, 'CHOOSE_EVENT', { id: 'medicine', choice: 'accept' });
  s = at(s, 'dock');
  const blocked = cmd(s, 'CHOOSE_EVENT', { id: 'medicine', choice: 'reason' });
  assert.equal(blocked.p0.quests.medicine.node, 'road');
  s.p0.knowledge = 3; s.p0.materials.herbs = 2;
  s = cmd(s, 'CHOOSE_EVENT', { id: 'medicine', choice: 'reason' });
  assert.equal(s.p0.quests.medicine.node, 'delivered'); assert.equal(s.p0.materials.herbs, 0);
  s = at(s, 'home');
  s = cmd(s, 'CHOOSE_EVENT', { id: 'medicine', choice: 'finish' });
  assert.ok(s.p0.facts.medicine_complete);
  assert.equal(cmd(s, 'CHOOSE_EVENT', { id: 'medicine', choice: 'finish' }).silver, s.silver);
  assert.ok(s.p0.journal.some(j => j.choiceId === 'reason' && j.result === 'success'));
  s = at(s, 'gym'); s = cmd(s, 'LEARN_SKILL', { id: 'huashan' });
  assert.ok(s.p0.styles['华山剑法']);
  assert.deepEqual(restore(s), { ...s, fx: null });
});
test('side battle restores its continuation, retreat opens repair and cannot duplicate story rewards', () => {
  let s = cmd(at(fresh(), 'pharmacy'), 'DISCOVER_EVENT', { id: 'medicine' });
  s = cmd(s, 'CHOOSE_EVENT', { id: 'medicine', choice: 'accept' });
  s = cmd(at(s, 'dock'), 'CHOOSE_EVENT', { id: 'medicine', choice: 'fight' });
  assert.equal(s.p0.quests.medicine.pending, 'fight');
  assert.deepEqual(advanceCombat(s, settleP0Combat), advanceCombat(restore(s), settleP0Combat));
  const escaped = retreatCombat(restore(s), settleP0Combat);
  assert.equal(escaped.p0.quests.medicine.node, 'repair'); assert.equal(escaped.p0.quests.medicine.pending, null);
  assert.equal(retreatCombat(escaped, settleP0Combat).silver, escaped.silver);
  assert.deepEqual(restore(escaped), { ...escaped, fx: null });
});
test('weapons and basic practice affect battle while free recovery prevents a resource dead end', () => {
  let s = { ...fresh(), hp: 1, mp: 0, silver: 0 };
  s = cmd(s, 'START_ACTIVITY', { id: 'rest' }); s = settleActivity(s, 251000);
  assert.equal(s.hp, 100); assert.equal(s.mp, 100); assert.equal(s.silver, 0);
  const base = startCombat(s), stronger = startCombat({ ...s, p0: { ...s.p0, weapon: 'practice', basics: { ...s.p0.basics, fist: 900 } } });
  assert.ok(stronger.battle.player.attack > base.battle.player.attack);
});
test('sect progression requires earned contribution, learned skill and successful exam', () => {
  let s = at(fresh(), 'wudang-gate', 1);
  s = cmd(s, 'JOIN_SECT'); s = at(s, 'wudang-yard', 1);
  s = cmd(s, 'START_ACTIVITY', { id: 'duty' }); s = settleActivity(s, 201000);
  s = cmd(s, 'LEARN_SKILL', { id: 'mianzhang' }, 201000);
  assert.ok(s.p0.styles['武当绵掌']);
  s = cmd(s, 'START_ACTIVITY', { id: 'style', target: '武当绵掌' }, 201000); s = settleActivity(s, 301000);
  assert.equal(s.training.styles['武当绵掌'], 80);
  s = cmd(s, 'START_ACTIVITY', { id: 'duty' }, 301000); s = settleActivity(s, 401000);
  s = cmd(s, 'START_ACTIVITY', { id: 'style', target: '武当绵掌' }, 401000); s = settleActivity(s, 421000);
  s = at(cmd(s, 'STOP_ACTIVITY', {}, 421000), 'wudang-hall', 1);
  s = cmd(s, 'EXAM', {}, 421000);
  assert.equal(s.battle.context.kind, 'side');
  assert.equal(s.battle.context.eventId, 'wudang_exam');
  const won = settleP0Combat({ ...s, action: null, battle: { ...s.battle, status: 'won', settled: true, result: '取胜' } }, { kind: 'exam' }, true);
  assert.equal(won.p0.rank, 1); assert.equal(won.p0.styles['武当绵掌'].cap, 3600);
  assert.equal(settleP0Combat(won, { kind: 'exam' }, true).p0.potential, won.p0.potential);
});
test('invalid activity targets and orphaned battle continuations are rejected by save migration', () => {
  let s = fresh(); s.p0.activity = { id: 'style', target: '不存在', settledAt: 1000, remainder: 0 };
  assert.throws(() => restore(s), /损坏/);
  s = fresh(); s.p0.quests.medicine = { node: 'road', pending: 'fight', done: false };
  assert.throws(() => restore(s), /缺失/);
  assert.ok(SIDE_EVENTS.medicine.nodes.repair.choices.every(c => c.next === 'road'));
});
test('complete legal command route earns, learns, trains, wins the actual escort and unlocks teaching', () => {
  const reducer = createGameReducer({ tick: state => state.action?.type === 'combat' ? advanceCombat(state, settleP0Combat) : state });
  let s = fresh(), now = 1000;
  const send = (type, fields = {}) => { s = reducer(s, { type, ...fields }, now); };
  const walk = (...rooms) => rooms.forEach(id => { send('MOVE_ROOM', { id }); assert.equal(s.p0.room, id); });
  walk('street', 'gym', 'dock');
  send('START_ACTIVITY', { id: 'work' }); now += 600000; send('HEARTBEAT');
  walk('gym'); send('LEARN_SKILL', { id: 'taizu' });
  send('START_ACTIVITY', { id: 'style', target: '太祖长拳' }); now += 100000; send('HEARTBEAT');
  send('EQUIP_LOADOUT', { loadout: { ...s.loadout, style: '太祖长拳' } });
  send('START_ACTIVITY', { id: 'rest' }); now += 100000; send('HEARTBEAT');
  walk('street', 'market', 'pharmacy'); send('DISCOVER_EVENT', { id: 'medicine' });
  send('CHOOSE_EVENT', { id: 'medicine', choice: 'accept' });
  walk('market', 'street', 'gym', 'dock'); send('CHOOSE_EVENT', { id: 'medicine', choice: 'fight' });
  s = restore(s);
  for (let i = 0; i < 60 && s.battle.status === 'active'; i++) { now += 1000; send('HEARTBEAT'); }
  assert.equal(s.battle.status, 'won'); assert.equal(s.p0.quests.medicine.node, 'delivered');
  assert.ok(s.mp < 100); send('CLOSE_COMBAT');
  walk('gym', 'street', 'inn', 'alley', 'home'); send('CHOOSE_EVENT', { id: 'medicine', choice: 'finish' });
  walk('alley', 'inn', 'street', 'gym'); send('LEARN_SKILL', { id: 'huashan' });
  assert.ok(s.p0.styles['华山剑法']); assert.ok(s.p0.facts.medicine_complete);
  assert.deepEqual(restore(s), { ...s, fx: null });
});
test('xiaoao pack events appear by zone, write numbered facts, and restore', () => {
  assert.ok(SIDE_EVENTS.xajh_z00_fuwei_waybill && SIDE_EVENTS.xajh_z02_songshan_post);
  assert.equal(Object.keys(PACK_EVENTS).every(id => SIDE_EVENTS[id]), true);
  assert.ok(Object.keys(PACK_EVENTS).length >= 13);
  let s = at(fresh(), 'dock');
  s = cmd(s, 'DISCOVER_EVENT', { id: 'xajh_z00_fuwei_waybill' });
  assert.equal(s.p0.quests.xajh_z00_fuwei_waybill.node, 'n0');
  s = { ...s, loc: 2 };
  s = cmd(s, 'DISCOVER_EVENT', { id: 'xajh_z02_songshan_post' });
  s = { ...s, p0: { ...s.p0, knowledge: 5, potential: 10 } };
  s = cmd(s, 'CHOOSE_EVENT', { id: 'xajh_z02_songshan_post', choice: 'xajh_z02_post_compared' });
  assert.equal(s.p0.facts.xajh_z02_post_compared, true);
  assert.equal(restore(s).p0.facts.xajh_z02_post_compared, true);
});
