// Original connective fiction. Book relationships are documented in gdd/14.
export const STORY_ARCS = {
  'YZ-01': { id:'yangzhou', actor:'韦小宝', zone:0, destination:3, stage:'随茅十八北行',
    preparation:'渡口安置', contact:'船户', trigger:2, decision:2,
    scene:'船户翻着渡簿，不肯让一个带伤的人挤进货舱。北门查得越紧，走水路越须有人作保。',
    motive:'小宝与茅十八要走，得先备一处不受盘查的落脚点。',
    help:'用盐号旧识核实船家，安置伤者', support:'letter_contact',
    consequence:'船家留出后舱，北门被围时可改走水路。',
    alternative:'凭渡簿从后埠撤出，护住茅十八', outcome:'船户认出你留下的记号，接走小宝与伤者。史松扑空，沿岸药铺继续接济北行旅客。',
    world:'canal_shelter', echo:'北行来信', returnScene:'北来的信上没有宫中奇闻，只有船户追问：那间安置伤者的后舱，还留不留？' },
  'FZ-01': { id:'fuwei', actor:'林平之', zone:0, destination:8, stage:'离开福州求生',
    preparation:'镖户避难', contact:'镖户遗属', trigger:1, decision:2,
    scene:'镖户抱着一册烧焦的货簿，巷口有人挨户问姓林的去向。卷宗与活人，只能先送走一头。',
    motive:'追索剑谱的人没有散，先把知道后门的镖户安顿下来。',
    help:'借护药人情，把镖户藏入药车', support:'medicine_complete',
    consequence:'镖户记下青城哨位，愿带林平之走避难路。',
    alternative:'循镖户暗记接出林平之，放弃正面冲关', outcome:'林平之随避难药车出城，遗属把空宅封好。活口留住了，青城的搜捕也有了可对质的证人。',
    world:'fuwei_refuge', echo:'华山来客', returnScene:'华山山脚来了福州口音的镖户。有人劝林平之只问剑谱，也有人拿着旧簿，等他认回故人的名字。' },
  'JX-01': { id:'zuixian', actor:'江南七怪', zone:0, destination:1, stage:'追查段天德去向',
    preparation:'法华寺车辙', contact:'寺外车夫', trigger:1, decision:3,
    scene:'车夫从轮毂刮下一点泥，指向后山芦苇。他怕说错一句，便把被押的妇人送进死路。',
    motive:'丘道长与七怪争的是旧怨，被押的家眷却还在车上。',
    help:'请盐号船户交叉核对车船去向', support:'letter_read',
    consequence:'车船记录排除了空车诱饵，能从后埠接出家眷。',
    alternative:'持车船证词请七怪分兵，先救家眷', outcome:'七怪循证词从后埠接出家眷，丘处机追赶押车军士。你没有替任何人许下十八年之约，只把活人的去向交清。',
    world:'family_shelter', echo:'寻亲口信', returnScene:'汉水渡口的寻亲告示换了新纸。七怪追查旧案的路尚长，获救家眷先需要一处能收到信的住处。' },
  'SZ-01': { id:'yanzi', actor:'阿朱', zone:0, destination:2, stage:'核对慕容家的嫌疑',
    preparation:'太湖往来簿', contact:'太湖船娘', trigger:1, decision:2,
    scene:'船娘将夜渡时辰写在旧帆布上。慕容家的名字人人会说，那晚究竟谁过湖，却少有人问。',
    motive:'马大元遇害的传闻越滚越大，船期只能证明行踪，不能凭空指认真凶。',
    help:'请安置过的伤者辨认当晚船只', support:'witness_sheltered',
    consequence:'阿朱收下船期副本，杏子林问案时多了一条可核实的证据。',
    alternative:'以往来簿说明来意，求阿朱共同核查', outcome:'阿朱答应替你核对渡簿，风波恶收刀让路。你们约定把可证实的行踪带往杏子林，不把猜疑写成罪名。',
    world:'lake_passage', echo:'阿朱的回话', returnScene:'中原茶棚有人带来阿朱的口信，询问杏子林究竟是在查死因，还是只拿血脉定罪。' },
  'HZ-01': { id:'meizhuang', actor:'黄钟公', zone:0, destination:12, stage:'梅庄四友殉职，遗事由琴铺旧人料理',
    preparation:'孤山退路', contact:'琴铺伙计', trigger:1, decision:2,
    scene:'琴铺伙计捧着断弦，担心梅庄一旦出事，四位老人连安身之处也没有。',
    motive:'向问天另有所图，留一条退路，才能让四友有拒绝的余地。',
    help:'借太湖船家的通行人情备好出海船', support:'lake_passage',
    consequence:'出海船只待手书，梅庄变局中可以护送四友撤走。',
    alternative:'启用海船退路，先护四友离庄', outcome:'黄钟公将琴交给伙计，随众人从侧门登船。任我行的争位另有去向，四友的生死没有被迫随之收束。',
    world:'meizhuang_survivors', repairWorld:'meizhuang_refuge', echo:'海上旧琴', returnScene:'琴铺伙计在海边留下口信，要核实四友是否脱身。若未能救出，便只为流落的旧仆安置住处，不再空许四友重聚。' },
  'WX-01': { id:'xingzi', actor:'乔峰', zone:0, destination:1, stage:'身世争议中的独立查证',
    preparation:'失踪帮众的家属', contact:'帮众家属', trigger:1, decision:2,
    scene:'家属攥着半截布条，求你先找到当夜守船的人。他若只剩一张口供，便再没人能追问细节。',
    motive:'有人用身世盖过死因。先保住见证者，再问他究竟看见了什么。',
    help:'请回春堂与武当接济并安置证人', support:'medicine_wudang',
    consequence:'证人可活着到场；太湖渡簿能替他的口供互相印证。',
    alternative:'将活证人与太湖渡簿同时交付，当众分清死因与身世', outcome:'见证者逐一对照渡簿。群丐同意先查失粮与凶案，不以血脉代替证据。乔峰留待会审，三帮仍须自行议定是否互认粮签。',
    world:'witness_sheltered', echo:'汉水证人安置', returnScene:'汉水堤边，证人的腿伤又发作了。三帮争执未停，愿不愿让他开口，也取决于有没有人替他守住退路。' },
  'DL-01': { id:'wuliang', actor:'钟灵', zone:11, destination:10, stage:'脱离神农营地',
    preparation:'神农药册', contact:'采药人', trigger:2, decision:4,
    scene:'采药人将药性相近的叶片分成两堆。烧了药库固然能乱敌，也会断掉山下病户的药。',
    motive:'钟灵还在营地，得把解毒药和下山的路一起备好。',
    help:'凭江南备药经验调出防毒药包', support:'medicine_prepared',
    consequence:'药包足够接应营中人，救人时可以避开纵火。',
    alternative:'用备药换取守营人让路，接出钟灵', outcome:'守营人接过对症药包，让开一条下山小径。钟灵平安离营，药库保全，神农病户也愿让药车经过。',
    world:'shennong_truce', echo:'万劫谷余波', returnScene:'云贵药市传来谷口争执的消息。钟灵已脱身，药库是否保全，却决定采药人肯不肯继续通商。' },
  'DL-02': { id:'nandi', actor:'一灯', zone:11, destination:0, stage:'救人之后闭关调养',
    preparation:'桃源护持', contact:'山下药童', trigger:1, decision:2,
    scene:'药童把干粮一份份分好，问上山的人能否帮忙守住山路。救人耗去的真气，靠一声谢可补不回来。',
    motive:'黄蓉等着救治，一灯也需要有人护持；瑛姑的旧怨不能靠旁人替她抹去。',
    help:'凭神农药路接来补给，留下护持的人', support:'shennong_truce',
    consequence:'山路与补给有了照应，瑛姑可以另约见面，救治先行。',
    alternative:'出示护持安排，请瑛姑另约清谈，先救伤者', outcome:'瑛姑收下会面的约期，退到山外。一灯先行救治，护持者守住桃源；旧怨仍在，今夜却不再拿伤者作筹码。',
    world:'taoyuan_shelter', echo:'桃源再约', returnScene:'江南来客捎来瑛姑的口信。她肯再问旧事，却不肯由旁人替她宣称已经释怀。' },
};
export const arcFact = (arc, suffix) => `${arc.id}_${suffix}`;
